### ISSUE TITLE
Where to download the plugin from?

### ISSUE THREAD

**Issue by rusergeev** [SonarQubeCommunity/sonar-activedirectory#11]
Hi,

It is maybe a stupid question. But I could not find where i can get the plugin to try it out.
Thanks.

**Comment by OrNol** [comment]
From the "Code" tab you can select the releases and download from there. Or go directly to:
https://github.com/SonarQubeCommunity/sonar-activedirectory/releases

**Comment by rusergeev** [comment]
thanks!
