### ISSUE TITLE
SonarException: Realm 'ACTIVE_DIRECTORY' not found

### ISSUE THREAD

**Issue by golayp** [SonarQubeCommunity/sonar-activedirectory#7]
Hello,

I'm trying to upgrade from ldap plugin 1.5.1 to 2.0 but when i follow instructions given, i receive the following exception on sonarqube startup:
Caused by: org.sonar.api.utils.SonarException: Realm 'ACTIVE_DIRECTORY' not found. Please check the property 'sonar.security.realm' in conf/sonar.properties

Did i miss something?

**Comment by pascalberger** [comment]
To use ACTIVE_DIRECTORY realm you need to install [this](https://github.com/SonarQubeCommunity/sonar-activedirectory/releases/tag/1.0) plugin and can uninstall the LDAP plugin afterwards.

**Comment by golayp** [comment]
Ok thanks you, I finally solved the problem by using the version 1.5.1 and configuring groups in sonarqube postfixed with the domain name like "mygroup@mydomain" ... 
But I definitely will give a try to this new plugin.
